# Code Snippets & Notes from Introduction to ML with Python

Example of a Numpy array. Converting data to NumPy arrays are required when using scikit-learn.

In [1]:
import numpy as np

x = np.array([[1,2,3], [4,5,6]])

print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


Example of a SciPy sparse matrix. Sparse matrices are used to store 2D arrays that contain mostly 0's.

In [2]:
from scipy import sparse

"""creates a 2D numpy array with a diagonal of ones and zero's everywhere. 
I need to find out what it's practical use is?"""

eye = np.eye(4)
print('NumPy array:\n{}'.format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
"""converting np array into a scipy sparse matrix in CSR format
so only nonzero entities are stored"""

sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
