# Code Snippets & Notes from Introduction to ML with Python

Example of a Numpy array. Converting data to NumPy arrays are required when using scikit-learn.

In [1]:
import numpy as np

x = np.array([[1,2,3], [4,5,6]])

print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


Example of a SciPy sparse matrix. Sparse matrices are used to store 2D arrays that contain mostly 0's.

In [2]:
from scipy import sparse

"""creates a 2D numpy array with a diagonal of ones and zero's everywhere. 
I need to find out what it's practical use is?"""

eye = np.eye(4)
print('NumPy array:\n{}'.format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
"""converting np array into a scipy sparse matrix in CSR format
so only nonzero entities are stored"""

sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


## I. Classification using the Iris dataset

In [2]:
from sklearn.datasets import load_iris

"""
This is a Bunch object that is similar to a dictionary
with keys and values
"""
iris_dataset = load_iris()

In [3]:
print("Kets of iris dataset: \n{}".format(iris_dataset.keys()))

Kets of iris dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:

print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========